#!/bin/sh

export AZURE_OPENAI_RESOURCE='cog-moww6huavlklg'
export AZURE_OPENAI_MODEL='chat'
export AZURE_OPENAI_KEY='67062ab6dcde4f9ab8243f04601e6e88'
export AZURE_OPENAI_MODEL_NAME='gpt-35-turbo'
export AZURE_OPENAI_TEMPERATURE='0.3'
export AZURE_SEARCH_SERVICE='gptkb-moww6huavlklg'
export AZURE_SEARCH_INDEX='people-culture-faq'
export AZURE_SEARCH_KEY='QqNRt5LDccm2evQgIViI3EYGJTmePwDPFkyqu1kQz8AzSeDK1oYt'
export AZURE_SEARCH_USE_SEMANTIC_SEARCH='True'
export AZURE_SEARCH_QUERY_TYPE='semantic'
export AZURE_SEARCH_ENABLE_IN_DOMAIN='True'
export AZURE_SEARCH_STRICTNESS='3'
export AZURE_SEARCH_CONTENT_COLUMNS='content'
export AZURE_SEARCH_FILENAME_COLUMN='filepath'
export AZURE_SEARCH_TITLE_COLUMN='title'
export AZURE_SEARCH_URL_COLUMN='url'
export DATASOURCE_TYPE='AzureCognitiveSearch'
export DEBUG='true'
export AZURE_OPENAI_SYSTEM_MESSAGE='Eres un asistente de recursos humanos. Tu respuesta debe ser en español y debe siempre empezar por estimado colaborador'
export AZURE_COSMOSDB_DATABASE='db_conversation_history'
export AZURE_COSMOSDB_ACCOUNT='db-people-culture-faq-test-1'
export AZURE_COSMOSDB_CONVERSATIONS_CONTAINER='conversations'
export AZURE_COSMOSDB_ACCOUNT_KEY='AISdVazt0TxQ9NVPzDP5PX4Sr1nYMmddwBCG9b7XuB5kYG68bIj1mjbTEN5cmwITrpSPM4fKXVPJACDbFSewSw=='

